export const JOIN_CHATROOM_START = 'JOIN_CHATROOM_START';
export const JOIN_CHATROOM_SUCCESS = 'JOIN_CHATROOM_SUCCESS';
export const JOIN_CHATROOM_ERROR = 'JOIN_CHATROOM_ERROR';

export const FETCH_CHATROOM_MESSAGES_START = 'FETCH_CHATROOM_MESSAGES_START';
export const FETCH_CHATROOM_MESSAGES_SUCCESS = 'FETCH_CHATROOM_MESSAGES_SUCCESS';
export const FETCH_CHATROOM_MESSAGES_ERROR = 'FETCH_CHATROOM_MESSAGES_ERROR';

export const FETCH_PARTIAL_CHATROOM_MESSAGES_START = 'FETCH_PARTIAL_CHATROOM_MESSAGES_START';
export const FETCH_PARTIAL_CHATROOM_MESSAGES_SUCCESS = 'FETCH_PARTIAL_CHATROOM_MESSAGES_SUCCESS';
export const FETCH_PARTIAL_CHATROOM_MESSAGES_ERROR = 'FETCH_PARTIAL_CHATROOM_MESSAGES_ERROR';

export const JOIN_CHATROOM = 'JOIN_CHATROOM';
export const LEAVE_CHATROOM = 'LEAVE_CHATROOM';

export const REFRESH_CHATROOM = 'REFRESH_CHATROOM';

export const UPDATE_USERS_COUNTER = 'UPDATE_USERS_COUNTER';

export const SEND_CHATROOM_MESSAGE = 'SEND_CHATROOM_MESSAGE';

export const RECEIVE_CHATROOM_MESSAGE = 'RECEIVE_CHATROOM_MESSAGE';